In [ ]:
#10*2 array form

In [21]:
import numpy as np

data = np.array([
    [1, 6012],
    [2, 7079],
    [3, 6886],
    [4, 7230],
    [5, 4598],
    [6, 5564],
    [7, 6971],
    [8, 7763],
    [9, 8032],
    [10, 9569]
])
print(data)



[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [22]:
# add 2000 steps

In [23]:
data[:, 1] += 2000
print(data)

[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [24]:
#more than 9000

In [30]:
steps= data[data[:, 1] > 9000,1]
print(steps)

[ 9079  9230  9763 10032 11569]


In [26]:
#sort

In [28]:
sorted = np.sort(data[:, 1])
print(sorted)

[ 6598  7564  8012  8886  8971  9079  9230  9763 10032 11569]
